directories:
  output: release/${version}
  buildResources: build
appId: com.zync.ssh
productName: Zync
linux:
  target:
    - AppImage
    - tar.gz
    - deb
  icon: public/icon.png
  category: Development
  executableName: zync
  maintainer: Gajendra <gajendravmy22@gmail.com>
mac:
  target:
    - zip
  icon: public/icon.png
  category: public.app-category.developer-tools
extraResources:
  - from: public/icon.png
    to: icon.png
win:
  target: nsis
  icon: public/icon.png
  artifactName: ${productName}-Setup-${version}.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  perMachine: false
files:
  - filter:
      - dist-electron/**/*
      - dist/**/*
      - package.json
publish:
  - provider: github
    owner: FDgajju
    repo: zync
electronVersion: 39.2.7
